install.packages("devtools")
devtools::install_github("devanshagr/PermutationTestSecond")
walmart <- read.csv("C:/Users/Rushabh/Downloads/WALMART1.csv")
View(walmart)

table(walmart$SODA, walmart$STEAK)
table(walmart$SODA, walmart$FISH)
table(walmart$SODA, walmart$COFFEE)
table(walmart$SODA, walmart$TEA)
table(walmart$SODA, walmart$COOKIES)
table(walmart$SODA, walmart$SALT)

table(walmart$STEAK, walmart$SODA)
table(walmart$STEAK, walmart$FISH)
table(walmart$STEAK, walmart$COFFEE)
table(walmart$STEAK, walmart$TEA)
table(walmart$STEAK, walmart$COOKIES)
table(walmart$STEAK, walmart$SALT)

table(walmart$FISH, walmart$SODA)
table(walmart$FISH, walmart$STEAK)
table(walmart$FISH, walmart$COFFEE)
table(walmart$FISH, walmart$TEA)
table(walmart$FISH, walmart$COOKIES)
table(walmart$FISH, walmart$SALT)

table(walmart$COFFEE, walmart$SODA)
table(walmart$COFFEE, walmart$STEAK)
table(walmart$COFFEE, walmart$FISH)
table(walmart$COFFEE, walmart$TEA)
table(walmart$COFFEE, walmart$COOKIES)
table(walmart$COFFEE, walmart$SALT)

table(walmart$TEA, walmart$SODA)
table(walmart$TEA, walmart$STEAK)
table(walmart$TEA, walmart$FISH)
table(walmart$TEA, walmart$COFFEE)
table(walmart$TEA, walmart$COOKIES)
table(walmart$TEA, walmart$SALT)

table(walmart$COOKIES, walmart$SODA)
table(walmart$COOKIES, walmart$STEAK)
table(walmart$COOKIES, walmart$FISH)
table(walmart$COOKIES, walmart$COFFEE)
table(walmart$COOKIES, walmart$TEA)
table(walmart$COOKIES, walmart$SALT)

table(walmart$SALT, walmart$SODA)
table(walmart$SALT, walmart$STEAK)
table(walmart$SALT, walmart$FISH)
table(walmart$SALT, walmart$COFFEE)
table(walmart$SALT, walmart$TEA)
table(walmart$SALT, walmart$COOKIES)

PermutationTestSecond::Permutation(walmart, "SODA", "FISH",1000, 0, 1)
PermutationTestSecond::Permutation(walmart, "SODA", "FISH",10000, 0, 1)
PermutationTestSecond::Permutation(walmart, "SODA", "COOKIES",10000, 0, 1)
PermutationTestSecond::Permutation(walmart, "SODA", "COOKIES",1000, 0, 1)
PermutationTestSecond::Permutation(walmart, "SODA", "COOKIES",100, 0, 1)
PermutationTestSecond::Permutation(walmart, "STEAK", "SODA",1000, 0, 1)
PermutationTestSecond::Permutation(walmart, "STEAK", "SODA",10000, 0, 1)
PermutationTestSecond::Permutation(walmart, "STEAK", "SODA",100, 0, 1)
PermutationTestSecond::Permutation(walmart, "STEAK", "SODA",10, 0, 1)
PermutationTestSecond::Permutation(walmart, "STEAK", "FISH",100, 0, 1)
PermutationTestSecond::Permutation(walmart, "STEAK", "FISH",1000, 0, 1)
PermutationTestSecond::Permutation(walmart, "STEAK", "FISH",10000, 0, 1)
PermutationTestSecond::Permutation(walmart, "FISH", "COOKIES",100, 0, 1)
PermutationTestSecond::Permutation(walmart, "FISH", "COOKIES",1000, 0, 1)
PermutationTestSecond::Permutation(walmart, "FISH", "COOKIES",10000, 0, 1)
PermutationTestSecond::Permutation(walmart, "FISH", "COOKIES",10, 0, 1)
PermutationTestSecond::Permutation(walmart, "COOKIES", "SODA",100, 0, 1)
PermutationTestSecond::Permutation(walmart, "COOKIES", "SODA",1000, 0, 1)
PermutationTestSecond::Permutation(walmart, "COOKIES", "SODA",10000, 0, 1)

